name = "emeditor-get-price"
main = "build/worker/shim.mjs"
compatibility_date = "2025-08-14"

[build]
command = "cargo install -q worker-build && worker-build --release"

[observability.logs]
enabled = true